plugins {
    id 'com.android.library'
}

group 'vgts.plugin.vgts_plugin'
version '1.0-SNAPSHOT'

android {
    namespace 'vgts.plugin.vgts_plugin'
    compileSdkVersion 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    defaultConfig {
        minSdkVersion 21
    }
}
